### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by khatchad** [citytechcia/Communitas#2]
Hey guys. Don't mean to open an issue up here but what's the status of this project?

**Comment by mdarefin** [comment]
Hi Professor Khatchadourian,

Due to class pressure the development is slow, and I am taking 7 classes
this semester, so not being really productive with the project. I have done
some back-end database work and
 work in the UI. Parsing the html of news-feed to the front page of the App
as side slide list view.

Thank you
Md Arefin
[image: Inline image 1]

**Comment by khatchad** [comment]
Understood! Thanks, @mdarefin.

**Comment by mdarefin** [comment]
Hi citytechcia/Communitas!

Your friend Shahrear has invited you to:

Flags Don't Matter
Black Bear Brooklyn - Brooklyn, NY

Tickets & More: http://www.bandsintown.com/event/10543791?artist=Flags%20Don%27t%20Matter&sender_id=6989416&came_from=197&utm_source=event_invitation&utm_medium=email_more&utm_campaign=Event%20Invitation

Seeya there,

~ Bandsintown Inc. © 2015 | http://bnds.in/HdWafg
215 Lexington Avenue, 18th floor New York, NY 10016
To unsubscribe http://mail.bandsintown.com/mpss/u/6gA/oi4VAA/t.1qb/mnOPTgGuQ3m9a0eRUzrbwA/ut18
